/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RequestInformationDTO { 
    nonFunctionalRequirement: string;
    architectureFamily: RequestInformationDTO.ArchitectureFamilyEnum;
    numOfResults: number;
}
export namespace RequestInformationDTO {
    export type ArchitectureFamilyEnum = 'CLASSIC_ARCHITECTURE' | 'QUANTUM_COMPUTING';
    export const ArchitectureFamilyEnum = {
        CLASSICARCHITECTURE: 'CLASSIC_ARCHITECTURE' as ArchitectureFamilyEnum,
        QUANTUMCOMPUTING: 'QUANTUM_COMPUTING' as ArchitectureFamilyEnum
    };
}